inherit_from: .relaxed-rubocop-2.4.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Include:
    - examples/**/*.rb
    - ruby/private/**/*.rb
  Exclude:
    - "bazel-*/**/*"
    - "**/external/**/*"
    - "**/rubocop"
    - "**/vendor/bundle/**/*"

Metrics/BlockLength:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table

Style/Dir:
  Enabled: false

# In Bazel we want to use __FILE__ because __dir__points to the actual sources
Style/ExpandPathArguments:
  Enabled: false

Style/StructInheritance:
  Enabled: false
