inherit_from: .relaxed-rubocop-2.4.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "**/rubocop"
    - "examples/**/*"
    - "bazel-*/**/*"
    - "**/external/**/*"
    - "**/vendor/bundle/**/*"

      
# In Bazel we want to use __FILE__ because __dir__points to the actual sources
Style/ExpandPathArguments:
  Enabled: false

Style/Dir:
  Enabled: false
