inherit_from: .relaxed-rubocop-2.4.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Include:
    - examples/**/*.rb
    - ruby/private/**/*.rb
  Exclude:
    - "bazel-*/**/*"
    - "**/external/**/*"
    - "**/rubocop"
    - "**/vendor/bundle/**/*"


Metrics/BlockLength:
  Enabled: false
