AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  mainInternalAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      EndpointConfiguration: PRIVATE
      TracingEnabled: true
      DefinitionBody:
        openapi: "3.0.0"
        paths:
          "/":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ main.Arn }/invocations
              responses: {}
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action:
                - "execute-api:Invoke"
              Resource: "execute-api:/*"
            - Effect: "Deny"
              Principal: "*"
              Action:
                - "execute-api:Invoke"
              Resource: "execute-api:/*"
              Condition:
                StringNotEquals:
                  aws:SourceVpc:
                    - "vpc-11111111"
                    - "vpc-22222222"
                    - "vpc-33333333"
  main:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lib/lambda.handler
      Runtime: ruby2.5
      Timeout: 30
      Tracing: "Active"
      Role: "DEFAULT"
      VpcConfig:
        SecurityGroupIds:
          - "DEFAULT"
        SubnetIds:
          - sub-A
          - sub-B
      Environment:
        Variables:
          TEST_ENVVAR:
      Events:
        InternalAPIget:
          Type: Api
          Properties:
            RestApiId: !Ref mainInternalAPI
            Path: /
            Method: GET

# Output names must match ^[a-zA-Z0-9]+$
Outputs:
  InternalAPIUrl:
    Description: Endpoint for internal API
    Value: !Sub "https://${ mainInternalAPI }.execute-api.${AWS::Region}.amazonaws.com/api"
