version: 2.1

jobs:
  rubocop: &bazel_defaults
    working_directory: /home/circleci/repo
    resource_class: medium
    docker:
      - image: bazelruby/ruby-2.6.5
    environment:
      PATH: "/usr/local/bin:/usr/bin:/sbin:/opt/bin:/home/circleci/repo/bin:/bin:/sbin:/usr/sbin"
      BUNDLE_PATH: /home/circleci/.bundle_cache
      BAZEL_OPTS: "--max_idle_secs=1 --host_jvm_args=-Xmx400m --host_jvm_args=-Xms400m"
      BAZEL_BUILD_OPTS: "--curses=no --verbose_failures --jobs 10"
      BAZEL_TEST_OPTS: "--verbose_failures --test_output=streamed --test_verbose_timeout_warnings "

    steps:
      - checkout

      - run:
          name: "Install ~/.bazelrc and run setup"
          command: |
            cp .circleci/.bazelrc ${HOME}
            /usr/bin/env bash bin/setup

      - run:
          name: Install Bundler
          command: |
            gem install bundler:2.0.2 --no-doc
            bundle install --jobs=4 --retry=3 --path ${BUNDLE_PATH}

      - run:
          name: "Rubocop Style Check"
          command: bundle exec rubocop -E -P

  bazel_build_workspace:
    <<: *bazel_defaults
    steps:
      - checkout

      - run:
          name: "Install ~/.bazelrc and run setup"
          command: |
            cp .circleci/.bazelrc ${HOME}
            /usr/bin/env bash bin/setup

      - run:
          name: "Bazel Build & Test Workspace"
          command: |
            /usr/bin/env bash bin/test-suite workspace

  bazel_ruby_package_zip:
    <<: *bazel_defaults
    steps:
      - checkout

      - run:
          name: "Install ~/.bazelrc and run setup"
          command: |
            cp .circleci/.bazelrc ${HOME}
            /usr/bin/env bash bin/setup

      - run:
          name: "Bazel Build & Test Workspace"
          command: |
            cd examples/simple_lambda && bazel ${BAZEL_OPTS} build ${BAZEL_BUILD_OPTS} -- :all

  bazel_build_examples:
    <<: *bazel_defaults

    steps:
      - checkout

      - run:
          name: "Install ~/.bazelrc and run setup"
          command: |
            cp .circleci/.bazelrc ${HOME}
            /usr/bin/env bash bin/setup

      - run:
          name: "Show Bazel Info"
          command: |
            /usr/bin/env bash bin/test-suite bazel-info

      - run:
          name: "Bazel Simple Script Example Build"
          command: |
            cd examples/simple_script && bazel ${BAZEL_OPTS} build ${BAZEL_BUILD_OPTS} -- //...

      - run:
          name: "Bazel Simple Script Example Test"
          command: |
            cd examples/simple_script && bazel ${BAZEL_OPTS} test ${BAZEL_BUILD_OPTS} ${BAZEL_TEST_OPTS} -- //...

      - run:
          name: "Bazel Simple Script Example Rubocop Check"
          command: |
            cd examples/simple_script && bazel ${BAZEL_OPTS} run ${BAZEL_BUILD_OPTS} -- :rubocop

  buildifier:
    <<: *bazel_defaults

    steps:
      - checkout

      - run:
          name: "Install ~/.bazelrc and run setup"
          command: |
            cp .circleci/.bazelrc ${HOME}
            /usr/bin/env bash bin/setup

      - run:
          name: "Bazel Buildifier Build"
          command: |
            bazel ${BAZEL_OPTS} build ${BAZEL_BUILD_OPTS} :buildifier-check

      - run:
          name: "Bazel Buildifier Run"
          command: |
            bazel ${BAZEL_OPTS} run   ${BAZEL_BUILD_OPTS} :buildifier-check

workflows:
  rules_ruby:
    jobs:
      - bazel_ruby_package_zip
      - bazel_build_workspace
      - bazel_build_examples
      - buildifier
